id = "october"
name = "October CMS"
version = "0.2.1"
schema_version = 1
authors = ["Devin Green <design@devingreen.me>"]
description = "Syntax highlighting for October CMS templates in Zed"
repository = "https://github.com/artistro08/zed-october"

[grammars.october]
repository = "https://github.com/artistro08/tree-sitter-october"
rev = "6085e31b3a904eb4f08b67fdd03f8436ee731825"

[grammars.ini]
repository = "https://github.com/justinmk/tree-sitter-ini"
rev = "e4018b5176132b4f3c5d6e61cea383f42288d0f5"

[grammars.twig]
repository = "https://github.com/gbprod/tree-sitter-twig"
rev = "0afd9a6d808944e65a7be393e31868b85345735f"
